public variable FILE_FLAGS = Assoc_Type[Integer_Type];

FILE_FLAGS[">"] = O_WRONLY|O_CREAT;
FILE_FLAGS[">|"] = O_WRONLY|O_TRUNC|O_CREAT;
FILE_FLAGS[">>"] = O_WRONLY|O_APPEND;
FILE_FLAGS[">>|"] =  O_WRONLY|O_APPEND|O_CREAT;

FILE_FLAGS["<"] = O_RDONLY;

FILE_FLAGS["<>"] = O_RDWR|O_CREAT;
FILE_FLAGS["<>|"] = O_RDWR|O_TRUNC|O_CREAT;
FILE_FLAGS["<>>"] = O_RDWR|O_APPEND;
FILE_FLAGS["<>>|"] =  O_RDWR|O_APPEND|O_CREAT;


