public variable PERM = Assoc_Type[Integer_Type];

PERM["PRIVATE"]  = S_IRWXU;
PERM["_PRIVATE"] = S_IRUSR|S_IWUSR;

PERM["STATIC"]   = PERM["PRIVATE"]|S_IRWXG;
PERM["_STATIC"]  = PERM["PRIVATE"]|S_IRGRP|S_IXGRP;
PERM["__STATIC"] = PERM["PRIVATE"]|S_IRGRP;

PERM["PUBLIC"]  = PERM["_STATIC"]|S_IROTH|S_IXOTH;
